# Generated by Django 6.0.4 on 2026-04-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sinav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Sınav Adı")),
                (
                    "aktif",
                    models.BooleanField(default=True, verbose_name="Sınav Aktif mi?"),
                ),
                (
                    "baslangic_tarihi",
                    models.DateTimeField(verbose_name="Başlangıç Zamanı"),
                ),
                ("sure", models.IntegerField(default=40, verbose_name="Süre (Dakika)")),
            ],
            options={
                "verbose_name": "Sınav",
                "verbose_name_plural": "Sınavlar",
            },
        ),
        migrations.CreateModel(
            name="Soru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metin", models.TextField(verbose_name="Soru Metni")),
                (
                    "puan_degeri",
                    models.IntegerField(default=10, verbose_name="Soru Puanı"),
                ),
                ("secenek_a", models.CharField(max_length=255, verbose_name="A Şıkkı")),
                ("secenek_b", models.CharField(max_length=255, verbose_name="B Şıkkı")),
                ("secenek_c", models.CharField(max_length=255, verbose_name="C Şıkkı")),
                ("secenek_d", models.CharField(max_length=255, verbose_name="D Şıkkı")),
                (
                    "dogru_cevap",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="Doğru Cevap Anahtarı",
                    ),
                ),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sorular",
                        to="ods_app.sinav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soru",
                "verbose_name_plural": "Sorular",
            },
        ),
        migrations.CreateModel(
            name="Sonuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ogrenci_no",
                    models.CharField(max_length=20, verbose_name="Öğrenci Numarası"),
                ),
                (
                    "puan",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Puan"
                    ),
                ),
                ("notlar", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "tarih",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sonuclar",
                        to="ods_app.sinav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sonuç",
                "verbose_name_plural": "Sonuçlar",
                "unique_together": {("ogrenci_no", "sinav")},
            },
        ),
    ]
