# Generated by Django 6.0.4 on 2026-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ods_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sonuc",
            name="cevaplar",
            field=models.JSONField(blank=True, default=dict, verbose_name="Cevaplar"),
        ),
        migrations.AddField(
            model_name="soru",
            name="ek_secenekler",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Varsa F, G, H... şeklinde ek seçenekler girin.",
                verbose_name="Ek Şıklar",
            ),
        ),
        migrations.AddField(
            model_name="soru",
            name="secenek_e",
            field=models.CharField(blank=True, max_length=255, verbose_name="E Şıkkı"),
        ),
        migrations.AddField(
            model_name="soru",
            name="soru_tipi",
            field=models.CharField(
                choices=[
                    ("MCQ", "Çoktan Seçmeli"),
                    ("FILL", "Boşluk Doldurma"),
                    ("ESSAY", "Klasik"),
                ],
                default="MCQ",
                max_length=10,
                verbose_name="Soru Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="soru",
            name="dogru_cevap",
            field=models.CharField(
                blank=True,
                help_text="MCQ için şık harfi; boşluk doldurma için doğru metin; klasik için isteğe bağlı.",
                max_length=255,
                verbose_name="Doğru Cevap",
            ),
        ),
        migrations.AlterField(
            model_name="soru",
            name="secenek_a",
            field=models.CharField(blank=True, max_length=255, verbose_name="A Şıkkı"),
        ),
        migrations.AlterField(
            model_name="soru",
            name="secenek_b",
            field=models.CharField(blank=True, max_length=255, verbose_name="B Şıkkı"),
        ),
        migrations.AlterField(
            model_name="soru",
            name="secenek_c",
            field=models.CharField(blank=True, max_length=255, verbose_name="C Şıkkı"),
        ),
        migrations.AlterField(
            model_name="soru",
            name="secenek_d",
            field=models.CharField(blank=True, max_length=255, verbose_name="D Şıkkı"),
        ),
    ]
